package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "napaonline")
public class Cart implements java.io.Serializable {

	private Long pk;
	private Long hjmpts;
	private Date createdts;
	private Date modifiedts;
	private Long typepkstring;
	private Long ownerpkstring;
	private Byte calculatedflag;
	private String code;
	private Long currencypk;
	private Long deliveryaddresspk;
	private BigDecimal deliverycost;
	private Long deliverymodepk;
	private Long deliverystatuspk;
	private String globaldiscountvalues;
	private Byte netflag;
	private Long paymentaddresspk;
	private BigDecimal paymentcost;
	private Long paymentinfopk;
	private Long paymentmodepk;
	private Long paymentstatuspk;
	private Long statuspk;
	private Long PExportstatus;
	private String statusinfo;
	private BigDecimal totalprice;
	private BigDecimal totaldiscounts;
	private BigDecimal totaltax;
	private String totaltaxvalues;
	private Long userpk;
	private BigDecimal subtotal;
	private Byte discountondelivery;
	private Byte discountonpayment;
	private Long PPreviousdeliverymode;
	private BigDecimal PTotalamountwithouttax;
	private byte[] PDeliverytaxvalues;
	private String PTrackingid;
	private Long PSite;
	private Long PStore;
	private String PGuid;
	private Long pickupinformation;
	private String purchaseid;
	private Byte aaaeligible;
	private byte[] orderheadervalues;
	private String PSessionid;
	private Date abandonmentemailtriggereddate;
	private Long aclts;
	private Long propts;
	private Long addlpickupperson;
	private Byte isguestorder;
	private String rewardstransactionloyaltyid;
	private Byte isillegibletosteal;
	private BigDecimal rewarddiscount;
	private String PDescription;
	private Date PExpirationtime;
	private String PName;
	private byte[] PEntrygroups;
	private Long PEurope1pricefactoryUdg;
	private Long PEurope1pricefactoryUpg;
	private Long PEurope1pricefactoryUtg;
	private String PQuotediscountvaluesinternal;
	private byte[] PAppliedcouponcodes;
	private String PCybsfingerprintsessionid;
	private Date PSavetime;
	private Long PSavedby;
	private Long PQuotereference;
	private Long PImportstatus;
	private Byte isillegibletorestore;
	private String investigationid;
	private String browseripaddress;
	private Long PSignifydfraudresult;
	private Byte isprofitshareenabled;
	private Byte retryrequired;
	private BigDecimal boltotal;
	private Set<Cartentry> cartentries = new HashSet<Cartentry>(0);

	public Cart() {
	}

	public Cart(Long hjmpts, Date createdts, Date modifiedts, Long typepkstring, Long ownerpkstring,
			Byte calculatedflag, String code, Long currencypk, Long deliveryaddresspk, BigDecimal deliverycost,
			Long deliverymodepk, Long deliverystatuspk, String globaldiscountvalues, Byte netflag,
			Long paymentaddresspk, BigDecimal paymentcost, Long paymentinfopk, Long paymentmodepk, Long paymentstatuspk,
			Long statuspk, Long PExportstatus, String statusinfo, BigDecimal totalprice, BigDecimal totaldiscounts,
			BigDecimal totaltax, String totaltaxvalues, Long userpk, BigDecimal subtotal, Byte discountondelivery,
			Byte discountonpayment, Long PPreviousdeliverymode, BigDecimal PTotalamountwithouttax,
			byte[] PDeliverytaxvalues, String PTrackingid, Long PSite, Long PStore, String PGuid,
			Long pickupinformation, String purchaseid, Byte aaaeligible, byte[] orderheadervalues, String PSessionid,
			Date abandonmentemailtriggereddate, Long aclts, Long propts, Long addlpickupperson, Byte isguestorder,
			String rewardstransactionloyaltyid, Byte isillegibletosteal, BigDecimal rewarddiscount, String PDescription,
			Date PExpirationtime, String PName, byte[] PEntrygroups, Long PEurope1pricefactoryUdg,
			Long PEurope1pricefactoryUpg, Long PEurope1pricefactoryUtg, String PQuotediscountvaluesinternal,
			byte[] PAppliedcouponcodes, String PCybsfingerprintsessionid, Date PSavetime, Long PSavedby,
			Long PQuotereference, Long PImportstatus, Byte isillegibletorestore, String investigationid,
			String browseripaddress, Long PSignifydfraudresult, Byte isprofitshareenabled, Byte retryrequired,
			BigDecimal boltotal, Set<Cartentry> cartentries) {
		this.hjmpts = hjmpts;
		this.createdts = createdts;
		this.modifiedts = modifiedts;
		this.typepkstring = typepkstring;
		this.ownerpkstring = ownerpkstring;
		this.calculatedflag = calculatedflag;
		this.code = code;
		this.currencypk = currencypk;
		this.deliveryaddresspk = deliveryaddresspk;
		this.deliverycost = deliverycost;
		this.deliverymodepk = deliverymodepk;
		this.deliverystatuspk = deliverystatuspk;
		this.globaldiscountvalues = globaldiscountvalues;
		this.netflag = netflag;
		this.paymentaddresspk = paymentaddresspk;
		this.paymentcost = paymentcost;
		this.paymentinfopk = paymentinfopk;
		this.paymentmodepk = paymentmodepk;
		this.paymentstatuspk = paymentstatuspk;
		this.statuspk = statuspk;
		this.PExportstatus = PExportstatus;
		this.statusinfo = statusinfo;
		this.totalprice = totalprice;
		this.totaldiscounts = totaldiscounts;
		this.totaltax = totaltax;
		this.totaltaxvalues = totaltaxvalues;
		this.userpk = userpk;
		this.subtotal = subtotal;
		this.discountondelivery = discountondelivery;
		this.discountonpayment = discountonpayment;
		this.PPreviousdeliverymode = PPreviousdeliverymode;
		this.PTotalamountwithouttax = PTotalamountwithouttax;
		this.PDeliverytaxvalues = PDeliverytaxvalues;
		this.PTrackingid = PTrackingid;
		this.PSite = PSite;
		this.PStore = PStore;
		this.PGuid = PGuid;
		this.pickupinformation = pickupinformation;
		this.purchaseid = purchaseid;
		this.aaaeligible = aaaeligible;
		this.orderheadervalues = orderheadervalues;
		this.PSessionid = PSessionid;
		this.abandonmentemailtriggereddate = abandonmentemailtriggereddate;
		this.aclts = aclts;
		this.propts = propts;
		this.addlpickupperson = addlpickupperson;
		this.isguestorder = isguestorder;
		this.rewardstransactionloyaltyid = rewardstransactionloyaltyid;
		this.isillegibletosteal = isillegibletosteal;
		this.rewarddiscount = rewarddiscount;
		this.PDescription = PDescription;
		this.PExpirationtime = PExpirationtime;
		this.PName = PName;
		this.PEntrygroups = PEntrygroups;
		this.PEurope1pricefactoryUdg = PEurope1pricefactoryUdg;
		this.PEurope1pricefactoryUpg = PEurope1pricefactoryUpg;
		this.PEurope1pricefactoryUtg = PEurope1pricefactoryUtg;
		this.PQuotediscountvaluesinternal = PQuotediscountvaluesinternal;
		this.PAppliedcouponcodes = PAppliedcouponcodes;
		this.PCybsfingerprintsessionid = PCybsfingerprintsessionid;
		this.PSavetime = PSavetime;
		this.PSavedby = PSavedby;
		this.PQuotereference = PQuotereference;
		this.PImportstatus = PImportstatus;
		this.isillegibletorestore = isillegibletorestore;
		this.investigationid = investigationid;
		this.browseripaddress = browseripaddress;
		this.PSignifydfraudresult = PSignifydfraudresult;
		this.isprofitshareenabled = isprofitshareenabled;
		this.retryrequired = retryrequired;
		this.boltotal = boltotal;
		this.cartentries = cartentries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PK", unique = true, nullable = false)
	public Long getPk() {
		return this.pk;
	}

	public void setPk(Long pk) {
		this.pk = pk;
	}

	@Column(name = "HJMPTS")
	public Long getHjmpts() {
		return this.hjmpts;
	}

	public void setHjmpts(Long hjmpts) {
		this.hjmpts = hjmpts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDTS", length = 26)
	public Date getCreatedts() {
		return this.createdts;
	}

	public void setCreatedts(Date createdts) {
		this.createdts = createdts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIEDTS", length = 26)
	public Date getModifiedts() {
		return this.modifiedts;
	}

	public void setModifiedts(Date modifiedts) {
		this.modifiedts = modifiedts;
	}

	@Column(name = "TYPEPKSTRING")
	public Long getTypepkstring() {
		return this.typepkstring;
	}

	public void setTypepkstring(Long typepkstring) {
		this.typepkstring = typepkstring;
	}

	@Column(name = "OWNERPKSTRING")
	public Long getOwnerpkstring() {
		return this.ownerpkstring;
	}

	public void setOwnerpkstring(Long ownerpkstring) {
		this.ownerpkstring = ownerpkstring;
	}

	@Column(name = "CALCULATEDFLAG")
	public Byte getCalculatedflag() {
		return this.calculatedflag;
	}

	public void setCalculatedflag(Byte calculatedflag) {
		this.calculatedflag = calculatedflag;
	}

	@Column(name = "CODE")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CURRENCYPK")
	public Long getCurrencypk() {
		return this.currencypk;
	}

	public void setCurrencypk(Long currencypk) {
		this.currencypk = currencypk;
	}

	@Column(name = "DELIVERYADDRESSPK")
	public Long getDeliveryaddresspk() {
		return this.deliveryaddresspk;
	}

	public void setDeliveryaddresspk(Long deliveryaddresspk) {
		this.deliveryaddresspk = deliveryaddresspk;
	}

	@Column(name = "DELIVERYCOST", precision = 30, scale = 8)
	public BigDecimal getDeliverycost() {
		return this.deliverycost;
	}

	public void setDeliverycost(BigDecimal deliverycost) {
		this.deliverycost = deliverycost;
	}

	@Column(name = "DELIVERYMODEPK")
	public Long getDeliverymodepk() {
		return this.deliverymodepk;
	}

	public void setDeliverymodepk(Long deliverymodepk) {
		this.deliverymodepk = deliverymodepk;
	}

	@Column(name = "DELIVERYSTATUSPK")
	public Long getDeliverystatuspk() {
		return this.deliverystatuspk;
	}

	public void setDeliverystatuspk(Long deliverystatuspk) {
		this.deliverystatuspk = deliverystatuspk;
	}

	@Column(name = "GLOBALDISCOUNTVALUES")
	public String getGlobaldiscountvalues() {
		return this.globaldiscountvalues;
	}

	public void setGlobaldiscountvalues(String globaldiscountvalues) {
		this.globaldiscountvalues = globaldiscountvalues;
	}

	@Column(name = "NETFLAG")
	public Byte getNetflag() {
		return this.netflag;
	}

	public void setNetflag(Byte netflag) {
		this.netflag = netflag;
	}

	@Column(name = "PAYMENTADDRESSPK")
	public Long getPaymentaddresspk() {
		return this.paymentaddresspk;
	}

	public void setPaymentaddresspk(Long paymentaddresspk) {
		this.paymentaddresspk = paymentaddresspk;
	}

	@Column(name = "PAYMENTCOST", precision = 30, scale = 8)
	public BigDecimal getPaymentcost() {
		return this.paymentcost;
	}

	public void setPaymentcost(BigDecimal paymentcost) {
		this.paymentcost = paymentcost;
	}

	@Column(name = "PAYMENTINFOPK")
	public Long getPaymentinfopk() {
		return this.paymentinfopk;
	}

	public void setPaymentinfopk(Long paymentinfopk) {
		this.paymentinfopk = paymentinfopk;
	}

	@Column(name = "PAYMENTMODEPK")
	public Long getPaymentmodepk() {
		return this.paymentmodepk;
	}

	public void setPaymentmodepk(Long paymentmodepk) {
		this.paymentmodepk = paymentmodepk;
	}

	@Column(name = "PAYMENTSTATUSPK")
	public Long getPaymentstatuspk() {
		return this.paymentstatuspk;
	}

	public void setPaymentstatuspk(Long paymentstatuspk) {
		this.paymentstatuspk = paymentstatuspk;
	}

	@Column(name = "STATUSPK")
	public Long getStatuspk() {
		return this.statuspk;
	}

	public void setStatuspk(Long statuspk) {
		this.statuspk = statuspk;
	}

	@Column(name = "P_EXPORTSTATUS")
	public Long getPExportstatus() {
		return this.PExportstatus;
	}

	public void setPExportstatus(Long PExportstatus) {
		this.PExportstatus = PExportstatus;
	}

	@Column(name = "STATUSINFO")
	public String getStatusinfo() {
		return this.statusinfo;
	}

	public void setStatusinfo(String statusinfo) {
		this.statusinfo = statusinfo;
	}

	@Column(name = "TOTALPRICE", precision = 30, scale = 8)
	public BigDecimal getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "TOTALDISCOUNTS", precision = 30, scale = 8)
	public BigDecimal getTotaldiscounts() {
		return this.totaldiscounts;
	}

	public void setTotaldiscounts(BigDecimal totaldiscounts) {
		this.totaldiscounts = totaldiscounts;
	}

	@Column(name = "TOTALTAX", precision = 30, scale = 8)
	public BigDecimal getTotaltax() {
		return this.totaltax;
	}

	public void setTotaltax(BigDecimal totaltax) {
		this.totaltax = totaltax;
	}

	@Column(name = "TOTALTAXVALUES")
	public String getTotaltaxvalues() {
		return this.totaltaxvalues;
	}

	public void setTotaltaxvalues(String totaltaxvalues) {
		this.totaltaxvalues = totaltaxvalues;
	}

	@Column(name = "USERPK")
	public Long getUserpk() {
		return this.userpk;
	}

	public void setUserpk(Long userpk) {
		this.userpk = userpk;
	}

	@Column(name = "SUBTOTAL", precision = 30, scale = 8)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "DISCOUNTONDELIVERY")
	public Byte getDiscountondelivery() {
		return this.discountondelivery;
	}

	public void setDiscountondelivery(Byte discountondelivery) {
		this.discountondelivery = discountondelivery;
	}

	@Column(name = "DISCOUNTONPAYMENT")
	public Byte getDiscountonpayment() {
		return this.discountonpayment;
	}

	public void setDiscountonpayment(Byte discountonpayment) {
		this.discountonpayment = discountonpayment;
	}

	@Column(name = "P_PREVIOUSDELIVERYMODE")
	public Long getPPreviousdeliverymode() {
		return this.PPreviousdeliverymode;
	}

	public void setPPreviousdeliverymode(Long PPreviousdeliverymode) {
		this.PPreviousdeliverymode = PPreviousdeliverymode;
	}

	@Column(name = "P_TOTALAMOUNTWITHOUTTAX", precision = 30, scale = 8)
	public BigDecimal getPTotalamountwithouttax() {
		return this.PTotalamountwithouttax;
	}

	public void setPTotalamountwithouttax(BigDecimal PTotalamountwithouttax) {
		this.PTotalamountwithouttax = PTotalamountwithouttax;
	}

	@Column(name = "P_DELIVERYTAXVALUES")
	public byte[] getPDeliverytaxvalues() {
		return this.PDeliverytaxvalues;
	}

	public void setPDeliverytaxvalues(byte[] PDeliverytaxvalues) {
		this.PDeliverytaxvalues = PDeliverytaxvalues;
	}

	@Column(name = "P_TRACKINGID")
	public String getPTrackingid() {
		return this.PTrackingid;
	}

	public void setPTrackingid(String PTrackingid) {
		this.PTrackingid = PTrackingid;
	}

	@Column(name = "P_SITE")
	public Long getPSite() {
		return this.PSite;
	}

	public void setPSite(Long PSite) {
		this.PSite = PSite;
	}

	@Column(name = "P_STORE")
	public Long getPStore() {
		return this.PStore;
	}

	public void setPStore(Long PStore) {
		this.PStore = PStore;
	}

	@Column(name = "P_GUID")
	public String getPGuid() {
		return this.PGuid;
	}

	public void setPGuid(String PGuid) {
		this.PGuid = PGuid;
	}

	@Column(name = "PICKUPINFORMATION")
	public Long getPickupinformation() {
		return this.pickupinformation;
	}

	public void setPickupinformation(Long pickupinformation) {
		this.pickupinformation = pickupinformation;
	}

	@Column(name = "PURCHASEID")
	public String getPurchaseid() {
		return this.purchaseid;
	}

	public void setPurchaseid(String purchaseid) {
		this.purchaseid = purchaseid;
	}

	@Column(name = "AAAELIGIBLE")
	public Byte getAaaeligible() {
		return this.aaaeligible;
	}

	public void setAaaeligible(Byte aaaeligible) {
		this.aaaeligible = aaaeligible;
	}

	@Column(name = "ORDERHEADERVALUES")
	public byte[] getOrderheadervalues() {
		return this.orderheadervalues;
	}

	public void setOrderheadervalues(byte[] orderheadervalues) {
		this.orderheadervalues = orderheadervalues;
	}

	@Column(name = "P_SESSIONID")
	public String getPSessionid() {
		return this.PSessionid;
	}

	public void setPSessionid(String PSessionid) {
		this.PSessionid = PSessionid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ABANDONMENTEMAILTRIGGEREDDATE", length = 26)
	public Date getAbandonmentemailtriggereddate() {
		return this.abandonmentemailtriggereddate;
	}

	public void setAbandonmentemailtriggereddate(Date abandonmentemailtriggereddate) {
		this.abandonmentemailtriggereddate = abandonmentemailtriggereddate;
	}

	@Column(name = "ACLTS")
	public Long getAclts() {
		return this.aclts;
	}

	public void setAclts(Long aclts) {
		this.aclts = aclts;
	}

	@Column(name = "PROPTS")
	public Long getPropts() {
		return this.propts;
	}

	public void setPropts(Long propts) {
		this.propts = propts;
	}

	@Column(name = "ADDLPICKUPPERSON")
	public Long getAddlpickupperson() {
		return this.addlpickupperson;
	}

	public void setAddlpickupperson(Long addlpickupperson) {
		this.addlpickupperson = addlpickupperson;
	}

	@Column(name = "ISGUESTORDER")
	public Byte getIsguestorder() {
		return this.isguestorder;
	}

	public void setIsguestorder(Byte isguestorder) {
		this.isguestorder = isguestorder;
	}

	@Column(name = "REWARDSTRANSACTIONLOYALTYID")
	public String getRewardstransactionloyaltyid() {
		return this.rewardstransactionloyaltyid;
	}

	public void setRewardstransactionloyaltyid(String rewardstransactionloyaltyid) {
		this.rewardstransactionloyaltyid = rewardstransactionloyaltyid;
	}

	@Column(name = "ISILLEGIBLETOSTEAL")
	public Byte getIsillegibletosteal() {
		return this.isillegibletosteal;
	}

	public void setIsillegibletosteal(Byte isillegibletosteal) {
		this.isillegibletosteal = isillegibletosteal;
	}

	@Column(name = "REWARDDISCOUNT", precision = 30, scale = 8)
	public BigDecimal getRewarddiscount() {
		return this.rewarddiscount;
	}

	public void setRewarddiscount(BigDecimal rewarddiscount) {
		this.rewarddiscount = rewarddiscount;
	}

	@Column(name = "P_DESCRIPTION", length = 65535)
	public String getPDescription() {
		return this.PDescription;
	}

	public void setPDescription(String PDescription) {
		this.PDescription = PDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_EXPIRATIONTIME", length = 26)
	public Date getPExpirationtime() {
		return this.PExpirationtime;
	}

	public void setPExpirationtime(Date PExpirationtime) {
		this.PExpirationtime = PExpirationtime;
	}

	@Column(name = "P_NAME", length = 65535)
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@Column(name = "P_ENTRYGROUPS")
	public byte[] getPEntrygroups() {
		return this.PEntrygroups;
	}

	public void setPEntrygroups(byte[] PEntrygroups) {
		this.PEntrygroups = PEntrygroups;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_UDG")
	public Long getPEurope1pricefactoryUdg() {
		return this.PEurope1pricefactoryUdg;
	}

	public void setPEurope1pricefactoryUdg(Long PEurope1pricefactoryUdg) {
		this.PEurope1pricefactoryUdg = PEurope1pricefactoryUdg;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_UPG")
	public Long getPEurope1pricefactoryUpg() {
		return this.PEurope1pricefactoryUpg;
	}

	public void setPEurope1pricefactoryUpg(Long PEurope1pricefactoryUpg) {
		this.PEurope1pricefactoryUpg = PEurope1pricefactoryUpg;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_UTG")
	public Long getPEurope1pricefactoryUtg() {
		return this.PEurope1pricefactoryUtg;
	}

	public void setPEurope1pricefactoryUtg(Long PEurope1pricefactoryUtg) {
		this.PEurope1pricefactoryUtg = PEurope1pricefactoryUtg;
	}

	@Column(name = "P_QUOTEDISCOUNTVALUESINTERNAL")
	public String getPQuotediscountvaluesinternal() {
		return this.PQuotediscountvaluesinternal;
	}

	public void setPQuotediscountvaluesinternal(String PQuotediscountvaluesinternal) {
		this.PQuotediscountvaluesinternal = PQuotediscountvaluesinternal;
	}

	@Column(name = "P_APPLIEDCOUPONCODES")
	public byte[] getPAppliedcouponcodes() {
		return this.PAppliedcouponcodes;
	}

	public void setPAppliedcouponcodes(byte[] PAppliedcouponcodes) {
		this.PAppliedcouponcodes = PAppliedcouponcodes;
	}

	@Column(name = "P_CYBSFINGERPRINTSESSIONID", length = 65535)
	public String getPCybsfingerprintsessionid() {
		return this.PCybsfingerprintsessionid;
	}

	public void setPCybsfingerprintsessionid(String PCybsfingerprintsessionid) {
		this.PCybsfingerprintsessionid = PCybsfingerprintsessionid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_SAVETIME", length = 26)
	public Date getPSavetime() {
		return this.PSavetime;
	}

	public void setPSavetime(Date PSavetime) {
		this.PSavetime = PSavetime;
	}

	@Column(name = "P_SAVEDBY")
	public Long getPSavedby() {
		return this.PSavedby;
	}

	public void setPSavedby(Long PSavedby) {
		this.PSavedby = PSavedby;
	}

	@Column(name = "P_QUOTEREFERENCE")
	public Long getPQuotereference() {
		return this.PQuotereference;
	}

	public void setPQuotereference(Long PQuotereference) {
		this.PQuotereference = PQuotereference;
	}

	@Column(name = "P_IMPORTSTATUS")
	public Long getPImportstatus() {
		return this.PImportstatus;
	}

	public void setPImportstatus(Long PImportstatus) {
		this.PImportstatus = PImportstatus;
	}

	@Column(name = "ISILLEGIBLETORESTORE")
	public Byte getIsillegibletorestore() {
		return this.isillegibletorestore;
	}

	public void setIsillegibletorestore(Byte isillegibletorestore) {
		this.isillegibletorestore = isillegibletorestore;
	}

	@Column(name = "INVESTIGATIONID", length = 65535)
	public String getInvestigationid() {
		return this.investigationid;
	}

	public void setInvestigationid(String investigationid) {
		this.investigationid = investigationid;
	}

	@Column(name = "BROWSERIPADDRESS", length = 65535)
	public String getBrowseripaddress() {
		return this.browseripaddress;
	}

	public void setBrowseripaddress(String browseripaddress) {
		this.browseripaddress = browseripaddress;
	}

	@Column(name = "P_SIGNIFYDFRAUDRESULT")
	public Long getPSignifydfraudresult() {
		return this.PSignifydfraudresult;
	}

	public void setPSignifydfraudresult(Long PSignifydfraudresult) {
		this.PSignifydfraudresult = PSignifydfraudresult;
	}

	@Column(name = "ISPROFITSHAREENABLED")
	public Byte getIsprofitshareenabled() {
		return this.isprofitshareenabled;
	}

	public void setIsprofitshareenabled(Byte isprofitshareenabled) {
		this.isprofitshareenabled = isprofitshareenabled;
	}

	@Column(name = "RETRYREQUIRED")
	public Byte getRetryrequired() {
		return this.retryrequired;
	}

	public void setRetryrequired(Byte retryrequired) {
		this.retryrequired = retryrequired;
	}

	@Column(name = "BOLTOTAL", precision = 30, scale = 8)
	public BigDecimal getBoltotal() {
		return this.boltotal;
	}

	public void setBoltotal(BigDecimal boltotal) {
		this.boltotal = boltotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
	public Set<Cartentry> getCartentries() {
		return this.cartentries;
	}

	public void setCartentries(Set<Cartentry> cartentries) {
		this.cartentries = cartentries;
	}

}
