package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cartentry generated by hbm2java
 */
@Entity
@Table(name = "cartentry", catalog = "napaonline")
public class Cartentry implements java.io.Serializable {

	private Long pk;
	private Cart cart;
	private Product product;
	private Long hjmpts;
	private Date createdts;
	private Date modifiedts;
	private Long typepkstring;
	private Long ownerpkstring;
	private BigDecimal baseprice;
	private Byte calculatedflag;
	private String discountvalues;
	private Long entrynumber;
	private String info;
	private BigDecimal quantity;
	private String taxvalues;
	private BigDecimal totalprice;
	private Long unitpk;
	private Byte giveawayflag;
	private Byte rejectedflag;
	private Long PChosenvendor;
	private Long PDeliveryaddress;
	private Long PDeliverymode;
	private Date PNameddeliverydate;
	private Long PQuantitystatus;
	private Byte PIsreturned;
	private BigDecimal POrderleveldiscountdistributi;
	private Long PDeliverypointofservice;
	private BigDecimal coreprice;
	private Long associatedvehicle;
	private Byte vehicleconditionsmet;
	private byte[] fitmentdetails;
	private byte[] vehicledetails;
	private String erecspec;
	private String productimportantinfo;
	private String productline;
	private String productname;
	private Long promotype;
	private BigDecimal promodiscount;
	private Byte isstockavailable;
	private Long PThumbnail;
	private String PThumbnailurl;
	private BigDecimal taxrate;
	private BigDecimal oldcoreprice;
	private BigDecimal oldbaseprice;
	private BigDecimal oldpromodiscount;
	private Long aclts;
	private Long propts;
	private Byte isstockavailablefromdc;
	private Byte isijoeiresponsefailed;
	private byte[] PEntrygroupnumbers;
	private Long PEurope1pricefactoryPpg;
	private Long PEurope1pricefactoryPtg;
	private Long PEurope1pricefactoryPdg;
	private Byte hasprop65;
	private String pdfprop65url;
	private String prop65warning;
	private String nsightmessage;

	public Cartentry() {
	}

	public Cartentry(Cart cart, Product product, Long hjmpts, Date createdts, Date modifiedts, Long typepkstring,
			Long ownerpkstring, BigDecimal baseprice, Byte calculatedflag, String discountvalues, Long entrynumber,
			String info, BigDecimal quantity, String taxvalues, BigDecimal totalprice, Long unitpk, Byte giveawayflag,
			Byte rejectedflag, Long PChosenvendor, Long PDeliveryaddress, Long PDeliverymode, Date PNameddeliverydate,
			Long PQuantitystatus, Byte PIsreturned, BigDecimal POrderleveldiscountdistributi,
			Long PDeliverypointofservice, BigDecimal coreprice, Long associatedvehicle, Byte vehicleconditionsmet,
			byte[] fitmentdetails, byte[] vehicledetails, String erecspec, String productimportantinfo,
			String productline, String productname, Long promotype, BigDecimal promodiscount, Byte isstockavailable,
			Long PThumbnail, String PThumbnailurl, BigDecimal taxrate, BigDecimal oldcoreprice, BigDecimal oldbaseprice,
			BigDecimal oldpromodiscount, Long aclts, Long propts, Byte isstockavailablefromdc,
			Byte isijoeiresponsefailed, byte[] PEntrygroupnumbers, Long PEurope1pricefactoryPpg,
			Long PEurope1pricefactoryPtg, Long PEurope1pricefactoryPdg, Byte hasprop65, String pdfprop65url,
			String prop65warning, String nsightmessage) {
		this.cart = cart;
		this.product = product;
		this.hjmpts = hjmpts;
		this.createdts = createdts;
		this.modifiedts = modifiedts;
		this.typepkstring = typepkstring;
		this.ownerpkstring = ownerpkstring;
		this.baseprice = baseprice;
		this.calculatedflag = calculatedflag;
		this.discountvalues = discountvalues;
		this.entrynumber = entrynumber;
		this.info = info;
		this.quantity = quantity;
		this.taxvalues = taxvalues;
		this.totalprice = totalprice;
		this.unitpk = unitpk;
		this.giveawayflag = giveawayflag;
		this.rejectedflag = rejectedflag;
		this.PChosenvendor = PChosenvendor;
		this.PDeliveryaddress = PDeliveryaddress;
		this.PDeliverymode = PDeliverymode;
		this.PNameddeliverydate = PNameddeliverydate;
		this.PQuantitystatus = PQuantitystatus;
		this.PIsreturned = PIsreturned;
		this.POrderleveldiscountdistributi = POrderleveldiscountdistributi;
		this.PDeliverypointofservice = PDeliverypointofservice;
		this.coreprice = coreprice;
		this.associatedvehicle = associatedvehicle;
		this.vehicleconditionsmet = vehicleconditionsmet;
		this.fitmentdetails = fitmentdetails;
		this.vehicledetails = vehicledetails;
		this.erecspec = erecspec;
		this.productimportantinfo = productimportantinfo;
		this.productline = productline;
		this.productname = productname;
		this.promotype = promotype;
		this.promodiscount = promodiscount;
		this.isstockavailable = isstockavailable;
		this.PThumbnail = PThumbnail;
		this.PThumbnailurl = PThumbnailurl;
		this.taxrate = taxrate;
		this.oldcoreprice = oldcoreprice;
		this.oldbaseprice = oldbaseprice;
		this.oldpromodiscount = oldpromodiscount;
		this.aclts = aclts;
		this.propts = propts;
		this.isstockavailablefromdc = isstockavailablefromdc;
		this.isijoeiresponsefailed = isijoeiresponsefailed;
		this.PEntrygroupnumbers = PEntrygroupnumbers;
		this.PEurope1pricefactoryPpg = PEurope1pricefactoryPpg;
		this.PEurope1pricefactoryPtg = PEurope1pricefactoryPtg;
		this.PEurope1pricefactoryPdg = PEurope1pricefactoryPdg;
		this.hasprop65 = hasprop65;
		this.pdfprop65url = pdfprop65url;
		this.prop65warning = prop65warning;
		this.nsightmessage = nsightmessage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PK", unique = true, nullable = false)
	public Long getPk() {
		return this.pk;
	}

	public void setPk(Long pk) {
		this.pk = pk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "P_ORDER")
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTPK")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "HJMPTS")
	public Long getHjmpts() {
		return this.hjmpts;
	}

	public void setHjmpts(Long hjmpts) {
		this.hjmpts = hjmpts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDTS", length = 26)
	public Date getCreatedts() {
		return this.createdts;
	}

	public void setCreatedts(Date createdts) {
		this.createdts = createdts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIEDTS", length = 26)
	public Date getModifiedts() {
		return this.modifiedts;
	}

	public void setModifiedts(Date modifiedts) {
		this.modifiedts = modifiedts;
	}

	@Column(name = "TYPEPKSTRING")
	public Long getTypepkstring() {
		return this.typepkstring;
	}

	public void setTypepkstring(Long typepkstring) {
		this.typepkstring = typepkstring;
	}

	@Column(name = "OWNERPKSTRING")
	public Long getOwnerpkstring() {
		return this.ownerpkstring;
	}

	public void setOwnerpkstring(Long ownerpkstring) {
		this.ownerpkstring = ownerpkstring;
	}

	@Column(name = "BASEPRICE", precision = 30, scale = 8)
	public BigDecimal getBaseprice() {
		return this.baseprice;
	}

	public void setBaseprice(BigDecimal baseprice) {
		this.baseprice = baseprice;
	}

	@Column(name = "CALCULATEDFLAG")
	public Byte getCalculatedflag() {
		return this.calculatedflag;
	}

	public void setCalculatedflag(Byte calculatedflag) {
		this.calculatedflag = calculatedflag;
	}

	@Column(name = "DISCOUNTVALUES")
	public String getDiscountvalues() {
		return this.discountvalues;
	}

	public void setDiscountvalues(String discountvalues) {
		this.discountvalues = discountvalues;
	}

	@Column(name = "ENTRYNUMBER")
	public Long getEntrynumber() {
		return this.entrynumber;
	}

	public void setEntrynumber(Long entrynumber) {
		this.entrynumber = entrynumber;
	}

	@Column(name = "INFO")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "QUANTITY", precision = 30, scale = 8)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "TAXVALUES")
	public String getTaxvalues() {
		return this.taxvalues;
	}

	public void setTaxvalues(String taxvalues) {
		this.taxvalues = taxvalues;
	}

	@Column(name = "TOTALPRICE", precision = 30, scale = 8)
	public BigDecimal getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "UNITPK")
	public Long getUnitpk() {
		return this.unitpk;
	}

	public void setUnitpk(Long unitpk) {
		this.unitpk = unitpk;
	}

	@Column(name = "GIVEAWAYFLAG")
	public Byte getGiveawayflag() {
		return this.giveawayflag;
	}

	public void setGiveawayflag(Byte giveawayflag) {
		this.giveawayflag = giveawayflag;
	}

	@Column(name = "REJECTEDFLAG")
	public Byte getRejectedflag() {
		return this.rejectedflag;
	}

	public void setRejectedflag(Byte rejectedflag) {
		this.rejectedflag = rejectedflag;
	}

	@Column(name = "P_CHOSENVENDOR")
	public Long getPChosenvendor() {
		return this.PChosenvendor;
	}

	public void setPChosenvendor(Long PChosenvendor) {
		this.PChosenvendor = PChosenvendor;
	}

	@Column(name = "P_DELIVERYADDRESS")
	public Long getPDeliveryaddress() {
		return this.PDeliveryaddress;
	}

	public void setPDeliveryaddress(Long PDeliveryaddress) {
		this.PDeliveryaddress = PDeliveryaddress;
	}

	@Column(name = "P_DELIVERYMODE")
	public Long getPDeliverymode() {
		return this.PDeliverymode;
	}

	public void setPDeliverymode(Long PDeliverymode) {
		this.PDeliverymode = PDeliverymode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_NAMEDDELIVERYDATE", length = 26)
	public Date getPNameddeliverydate() {
		return this.PNameddeliverydate;
	}

	public void setPNameddeliverydate(Date PNameddeliverydate) {
		this.PNameddeliverydate = PNameddeliverydate;
	}

	@Column(name = "P_QUANTITYSTATUS")
	public Long getPQuantitystatus() {
		return this.PQuantitystatus;
	}

	public void setPQuantitystatus(Long PQuantitystatus) {
		this.PQuantitystatus = PQuantitystatus;
	}

	@Column(name = "P_ISRETURNED")
	public Byte getPIsreturned() {
		return this.PIsreturned;
	}

	public void setPIsreturned(Byte PIsreturned) {
		this.PIsreturned = PIsreturned;
	}

	@Column(name = "P_ORDERLEVELDISCOUNTDISTRIBUTI", precision = 30, scale = 8)
	public BigDecimal getPOrderleveldiscountdistributi() {
		return this.POrderleveldiscountdistributi;
	}

	public void setPOrderleveldiscountdistributi(BigDecimal POrderleveldiscountdistributi) {
		this.POrderleveldiscountdistributi = POrderleveldiscountdistributi;
	}

	@Column(name = "P_DELIVERYPOINTOFSERVICE")
	public Long getPDeliverypointofservice() {
		return this.PDeliverypointofservice;
	}

	public void setPDeliverypointofservice(Long PDeliverypointofservice) {
		this.PDeliverypointofservice = PDeliverypointofservice;
	}

	@Column(name = "COREPRICE", precision = 30, scale = 8)
	public BigDecimal getCoreprice() {
		return this.coreprice;
	}

	public void setCoreprice(BigDecimal coreprice) {
		this.coreprice = coreprice;
	}

	@Column(name = "ASSOCIATEDVEHICLE")
	public Long getAssociatedvehicle() {
		return this.associatedvehicle;
	}

	public void setAssociatedvehicle(Long associatedvehicle) {
		this.associatedvehicle = associatedvehicle;
	}

	@Column(name = "VEHICLECONDITIONSMET")
	public Byte getVehicleconditionsmet() {
		return this.vehicleconditionsmet;
	}

	public void setVehicleconditionsmet(Byte vehicleconditionsmet) {
		this.vehicleconditionsmet = vehicleconditionsmet;
	}

	@Column(name = "FITMENTDETAILS")
	public byte[] getFitmentdetails() {
		return this.fitmentdetails;
	}

	public void setFitmentdetails(byte[] fitmentdetails) {
		this.fitmentdetails = fitmentdetails;
	}

	@Column(name = "VEHICLEDETAILS")
	public byte[] getVehicledetails() {
		return this.vehicledetails;
	}

	public void setVehicledetails(byte[] vehicledetails) {
		this.vehicledetails = vehicledetails;
	}

	@Column(name = "ERECSPEC")
	public String getErecspec() {
		return this.erecspec;
	}

	public void setErecspec(String erecspec) {
		this.erecspec = erecspec;
	}

	@Column(name = "PRODUCTIMPORTANTINFO")
	public String getProductimportantinfo() {
		return this.productimportantinfo;
	}

	public void setProductimportantinfo(String productimportantinfo) {
		this.productimportantinfo = productimportantinfo;
	}

	@Column(name = "PRODUCTLINE")
	public String getProductline() {
		return this.productline;
	}

	public void setProductline(String productline) {
		this.productline = productline;
	}

	@Column(name = "PRODUCTNAME")
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "PROMOTYPE")
	public Long getPromotype() {
		return this.promotype;
	}

	public void setPromotype(Long promotype) {
		this.promotype = promotype;
	}

	@Column(name = "PROMODISCOUNT", precision = 30, scale = 8)
	public BigDecimal getPromodiscount() {
		return this.promodiscount;
	}

	public void setPromodiscount(BigDecimal promodiscount) {
		this.promodiscount = promodiscount;
	}

	@Column(name = "ISSTOCKAVAILABLE")
	public Byte getIsstockavailable() {
		return this.isstockavailable;
	}

	public void setIsstockavailable(Byte isstockavailable) {
		this.isstockavailable = isstockavailable;
	}

	@Column(name = "P_THUMBNAIL")
	public Long getPThumbnail() {
		return this.PThumbnail;
	}

	public void setPThumbnail(Long PThumbnail) {
		this.PThumbnail = PThumbnail;
	}

	@Column(name = "P_THUMBNAILURL")
	public String getPThumbnailurl() {
		return this.PThumbnailurl;
	}

	public void setPThumbnailurl(String PThumbnailurl) {
		this.PThumbnailurl = PThumbnailurl;
	}

	@Column(name = "TAXRATE", precision = 30, scale = 8)
	public BigDecimal getTaxrate() {
		return this.taxrate;
	}

	public void setTaxrate(BigDecimal taxrate) {
		this.taxrate = taxrate;
	}

	@Column(name = "OLDCOREPRICE", precision = 30, scale = 8)
	public BigDecimal getOldcoreprice() {
		return this.oldcoreprice;
	}

	public void setOldcoreprice(BigDecimal oldcoreprice) {
		this.oldcoreprice = oldcoreprice;
	}

	@Column(name = "OLDBASEPRICE", precision = 30, scale = 8)
	public BigDecimal getOldbaseprice() {
		return this.oldbaseprice;
	}

	public void setOldbaseprice(BigDecimal oldbaseprice) {
		this.oldbaseprice = oldbaseprice;
	}

	@Column(name = "OLDPROMODISCOUNT", precision = 30, scale = 8)
	public BigDecimal getOldpromodiscount() {
		return this.oldpromodiscount;
	}

	public void setOldpromodiscount(BigDecimal oldpromodiscount) {
		this.oldpromodiscount = oldpromodiscount;
	}

	@Column(name = "ACLTS")
	public Long getAclts() {
		return this.aclts;
	}

	public void setAclts(Long aclts) {
		this.aclts = aclts;
	}

	@Column(name = "PROPTS")
	public Long getPropts() {
		return this.propts;
	}

	public void setPropts(Long propts) {
		this.propts = propts;
	}

	@Column(name = "ISSTOCKAVAILABLEFROMDC")
	public Byte getIsstockavailablefromdc() {
		return this.isstockavailablefromdc;
	}

	public void setIsstockavailablefromdc(Byte isstockavailablefromdc) {
		this.isstockavailablefromdc = isstockavailablefromdc;
	}

	@Column(name = "ISIJOEIRESPONSEFAILED")
	public Byte getIsijoeiresponsefailed() {
		return this.isijoeiresponsefailed;
	}

	public void setIsijoeiresponsefailed(Byte isijoeiresponsefailed) {
		this.isijoeiresponsefailed = isijoeiresponsefailed;
	}

	@Column(name = "P_ENTRYGROUPNUMBERS")
	public byte[] getPEntrygroupnumbers() {
		return this.PEntrygroupnumbers;
	}

	public void setPEntrygroupnumbers(byte[] PEntrygroupnumbers) {
		this.PEntrygroupnumbers = PEntrygroupnumbers;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_PPG")
	public Long getPEurope1pricefactoryPpg() {
		return this.PEurope1pricefactoryPpg;
	}

	public void setPEurope1pricefactoryPpg(Long PEurope1pricefactoryPpg) {
		this.PEurope1pricefactoryPpg = PEurope1pricefactoryPpg;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_PTG")
	public Long getPEurope1pricefactoryPtg() {
		return this.PEurope1pricefactoryPtg;
	}

	public void setPEurope1pricefactoryPtg(Long PEurope1pricefactoryPtg) {
		this.PEurope1pricefactoryPtg = PEurope1pricefactoryPtg;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_PDG")
	public Long getPEurope1pricefactoryPdg() {
		return this.PEurope1pricefactoryPdg;
	}

	public void setPEurope1pricefactoryPdg(Long PEurope1pricefactoryPdg) {
		this.PEurope1pricefactoryPdg = PEurope1pricefactoryPdg;
	}

	@Column(name = "HASPROP65")
	public Byte getHasprop65() {
		return this.hasprop65;
	}

	public void setHasprop65(Byte hasprop65) {
		this.hasprop65 = hasprop65;
	}

	@Column(name = "PDFPROP65URL", length = 65535)
	public String getPdfprop65url() {
		return this.pdfprop65url;
	}

	public void setPdfprop65url(String pdfprop65url) {
		this.pdfprop65url = pdfprop65url;
	}

	@Column(name = "PROP65WARNING", length = 65535)
	public String getProp65warning() {
		return this.prop65warning;
	}

	public void setProp65warning(String prop65warning) {
		this.prop65warning = prop65warning;
	}

	@Column(name = "NSIGHTMESSAGE", length = 65535)
	public String getNsightmessage() {
		return this.nsightmessage;
	}

	public void setNsightmessage(String nsightmessage) {
		this.nsightmessage = nsightmessage;
	}

}
