package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerVehicleId generated by hbm2java
 */
@Embeddable
public class CustomerVehicleId implements java.io.Serializable {

	private long customerId;
	private long vehicleId;

	public CustomerVehicleId() {
	}

	public CustomerVehicleId(long customerId, long vehicleId) {
		this.customerId = customerId;
		this.vehicleId = vehicleId;
	}

	@Column(name = "customer_id", nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "vehicle_id", nullable = false)
	public long getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(long vehicleId) {
		this.vehicleId = vehicleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerVehicleId))
			return false;
		CustomerVehicleId castOther = (CustomerVehicleId) other;

		return (this.getCustomerId() == castOther.getCustomerId()) && (this.getVehicleId() == castOther.getVehicleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCustomerId();
		result = 37 * result + (int) this.getVehicleId();
		return result;
	}

}
