package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CustomerDefaultVehicle generated by hbm2java
 */
@Entity
@Table(name = "customer_default_vehicle", catalog = "napaonline", uniqueConstraints = @UniqueConstraint(columnNames = "vehicle_id"))
public class CustomerDefaultVehicle implements java.io.Serializable {

	private long customerId;
	private Customer customer;
	private Vehicle vehicle;

	public CustomerDefaultVehicle() {
	}

	public CustomerDefaultVehicle(Customer customer, Vehicle vehicle) {
		this.customer = customer;
		this.vehicle = vehicle;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "customer"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "customer_id", unique = true, nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_id", unique = true, nullable = false)
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

}
