package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerVehicle generated by hbm2java
 */
@Entity
@Table(name = "customer_vehicle", catalog = "napaonline")
public class CustomerVehicle implements java.io.Serializable {

	private CustomerVehicleId id;
	private Customer customer;
	private Vehicle vehicle;

	public CustomerVehicle() {
	}

	public CustomerVehicle(CustomerVehicleId id, Customer customer, Vehicle vehicle) {
		this.id = id;
		this.customer = customer;
		this.vehicle = vehicle;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "customer_id", nullable = false)),
			@AttributeOverride(name = "vehicleId", column = @Column(name = "vehicle_id", nullable = false)) })
	public CustomerVehicleId getId() {
		return this.id;
	}

	public void setId(CustomerVehicleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false, insertable = false, updatable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_id", nullable = false, insertable = false, updatable = false)
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

}
