package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "napaonline")
public class Product implements java.io.Serializable {

	private Long pk;
	private Long hjmpts;
	private Date createdts;
	private Date modifiedts;
	private Long typepkstring;
	private Long ownerpkstring;
	private String code;
	private Long unitpk;
	private Long PThumbnail;
	private Long PPicture;
	private Long PCatalog;
	private Long PCatalogversion;
	private Date POnlinedate;
	private Date POfflinedate;
	private String PEan;
	private String PSupplieralternativeaid;
	private byte[] PBuyerids;
	private String PManufactureraid;
	private String PManufacturername;
	private String PErpgroupbuyer;
	private String PErpgroupsupplier;
	private BigDecimal PDeliverytime;
	private byte[] PSpecialtreatmentclasses;
	private Long POrder;
	private Long PApprovalstatus;
	private Long PContentunit;
	private BigDecimal PNumbercontentunits;
	private Long PMinorderquantity;
	private Long PMaxorderquantity;
	private Long POrderquantityinterval;
	private BigDecimal PPricequantity;
	private String PNormal;
	private String PThumbnails;
	private String PDetail;
	private String PLogo;
	private String PDataSheet;
	private String POthers;
	private Long PStartlinenumber;
	private Long PEndlinenumber;
	private Long PVarianttype;
	private Long PEurope1pricefactoryPpg;
	private Long PEurope1pricefactoryPtg;
	private Long PEurope1pricefactoryPdg;
	private Long PProductorderlimit;
	private String PTaxcode;
	private String PGalleryimages;
	private Long PSequenceid;
	private Long aclts;
	private Long propts;
	private Long PBaseproduct;
	private Long PPreviousbaseproduct;
	private String hqabbr;
	private String partnumber;
	private String lineabbr;
	private Byte isshippable;
	private String msds;
	private String jstdpkg;
	private String dcuom;
	private String cls;
	private String grpcode;
	private String weight;
	private String width;
	private String length;
	private String height;
	private Byte PIssellabletoconsumer;
	private Set<Cartentry> cartentries = new HashSet<Cartentry>(0);

	public Product() {
	}

	public Product(Long hjmpts, Date createdts, Date modifiedts, Long typepkstring, Long ownerpkstring, String code,
			Long unitpk, Long PThumbnail, Long PPicture, Long PCatalog, Long PCatalogversion, Date POnlinedate,
			Date POfflinedate, String PEan, String PSupplieralternativeaid, byte[] PBuyerids, String PManufactureraid,
			String PManufacturername, String PErpgroupbuyer, String PErpgroupsupplier, BigDecimal PDeliverytime,
			byte[] PSpecialtreatmentclasses, Long POrder, Long PApprovalstatus, Long PContentunit,
			BigDecimal PNumbercontentunits, Long PMinorderquantity, Long PMaxorderquantity, Long POrderquantityinterval,
			BigDecimal PPricequantity, String PNormal, String PThumbnails, String PDetail, String PLogo,
			String PDataSheet, String POthers, Long PStartlinenumber, Long PEndlinenumber, Long PVarianttype,
			Long PEurope1pricefactoryPpg, Long PEurope1pricefactoryPtg, Long PEurope1pricefactoryPdg,
			Long PProductorderlimit, String PTaxcode, String PGalleryimages, Long PSequenceid, Long aclts, Long propts,
			Long PBaseproduct, Long PPreviousbaseproduct, String hqabbr, String partnumber, String lineabbr,
			Byte isshippable, String msds, String jstdpkg, String dcuom, String cls, String grpcode, String weight,
			String width, String length, String height, Byte PIssellabletoconsumer, Set<Cartentry> cartentries) {
		this.hjmpts = hjmpts;
		this.createdts = createdts;
		this.modifiedts = modifiedts;
		this.typepkstring = typepkstring;
		this.ownerpkstring = ownerpkstring;
		this.code = code;
		this.unitpk = unitpk;
		this.PThumbnail = PThumbnail;
		this.PPicture = PPicture;
		this.PCatalog = PCatalog;
		this.PCatalogversion = PCatalogversion;
		this.POnlinedate = POnlinedate;
		this.POfflinedate = POfflinedate;
		this.PEan = PEan;
		this.PSupplieralternativeaid = PSupplieralternativeaid;
		this.PBuyerids = PBuyerids;
		this.PManufactureraid = PManufactureraid;
		this.PManufacturername = PManufacturername;
		this.PErpgroupbuyer = PErpgroupbuyer;
		this.PErpgroupsupplier = PErpgroupsupplier;
		this.PDeliverytime = PDeliverytime;
		this.PSpecialtreatmentclasses = PSpecialtreatmentclasses;
		this.POrder = POrder;
		this.PApprovalstatus = PApprovalstatus;
		this.PContentunit = PContentunit;
		this.PNumbercontentunits = PNumbercontentunits;
		this.PMinorderquantity = PMinorderquantity;
		this.PMaxorderquantity = PMaxorderquantity;
		this.POrderquantityinterval = POrderquantityinterval;
		this.PPricequantity = PPricequantity;
		this.PNormal = PNormal;
		this.PThumbnails = PThumbnails;
		this.PDetail = PDetail;
		this.PLogo = PLogo;
		this.PDataSheet = PDataSheet;
		this.POthers = POthers;
		this.PStartlinenumber = PStartlinenumber;
		this.PEndlinenumber = PEndlinenumber;
		this.PVarianttype = PVarianttype;
		this.PEurope1pricefactoryPpg = PEurope1pricefactoryPpg;
		this.PEurope1pricefactoryPtg = PEurope1pricefactoryPtg;
		this.PEurope1pricefactoryPdg = PEurope1pricefactoryPdg;
		this.PProductorderlimit = PProductorderlimit;
		this.PTaxcode = PTaxcode;
		this.PGalleryimages = PGalleryimages;
		this.PSequenceid = PSequenceid;
		this.aclts = aclts;
		this.propts = propts;
		this.PBaseproduct = PBaseproduct;
		this.PPreviousbaseproduct = PPreviousbaseproduct;
		this.hqabbr = hqabbr;
		this.partnumber = partnumber;
		this.lineabbr = lineabbr;
		this.isshippable = isshippable;
		this.msds = msds;
		this.jstdpkg = jstdpkg;
		this.dcuom = dcuom;
		this.cls = cls;
		this.grpcode = grpcode;
		this.weight = weight;
		this.width = width;
		this.length = length;
		this.height = height;
		this.PIssellabletoconsumer = PIssellabletoconsumer;
		this.cartentries = cartentries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PK", unique = true, nullable = false)
	public Long getPk() {
		return this.pk;
	}

	public void setPk(Long pk) {
		this.pk = pk;
	}

	@Column(name = "HJMPTS")
	public Long getHjmpts() {
		return this.hjmpts;
	}

	public void setHjmpts(Long hjmpts) {
		this.hjmpts = hjmpts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDTS", length = 26)
	public Date getCreatedts() {
		return this.createdts;
	}

	public void setCreatedts(Date createdts) {
		this.createdts = createdts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIEDTS", length = 26)
	public Date getModifiedts() {
		return this.modifiedts;
	}

	public void setModifiedts(Date modifiedts) {
		this.modifiedts = modifiedts;
	}

	@Column(name = "TYPEPKSTRING")
	public Long getTypepkstring() {
		return this.typepkstring;
	}

	public void setTypepkstring(Long typepkstring) {
		this.typepkstring = typepkstring;
	}

	@Column(name = "OWNERPKSTRING")
	public Long getOwnerpkstring() {
		return this.ownerpkstring;
	}

	public void setOwnerpkstring(Long ownerpkstring) {
		this.ownerpkstring = ownerpkstring;
	}

	@Column(name = "CODE")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "UNITPK")
	public Long getUnitpk() {
		return this.unitpk;
	}

	public void setUnitpk(Long unitpk) {
		this.unitpk = unitpk;
	}

	@Column(name = "P_THUMBNAIL")
	public Long getPThumbnail() {
		return this.PThumbnail;
	}

	public void setPThumbnail(Long PThumbnail) {
		this.PThumbnail = PThumbnail;
	}

	@Column(name = "P_PICTURE")
	public Long getPPicture() {
		return this.PPicture;
	}

	public void setPPicture(Long PPicture) {
		this.PPicture = PPicture;
	}

	@Column(name = "P_CATALOG")
	public Long getPCatalog() {
		return this.PCatalog;
	}

	public void setPCatalog(Long PCatalog) {
		this.PCatalog = PCatalog;
	}

	@Column(name = "P_CATALOGVERSION")
	public Long getPCatalogversion() {
		return this.PCatalogversion;
	}

	public void setPCatalogversion(Long PCatalogversion) {
		this.PCatalogversion = PCatalogversion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_ONLINEDATE", length = 26)
	public Date getPOnlinedate() {
		return this.POnlinedate;
	}

	public void setPOnlinedate(Date POnlinedate) {
		this.POnlinedate = POnlinedate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_OFFLINEDATE", length = 26)
	public Date getPOfflinedate() {
		return this.POfflinedate;
	}

	public void setPOfflinedate(Date POfflinedate) {
		this.POfflinedate = POfflinedate;
	}

	@Column(name = "P_EAN")
	public String getPEan() {
		return this.PEan;
	}

	public void setPEan(String PEan) {
		this.PEan = PEan;
	}

	@Column(name = "P_SUPPLIERALTERNATIVEAID")
	public String getPSupplieralternativeaid() {
		return this.PSupplieralternativeaid;
	}

	public void setPSupplieralternativeaid(String PSupplieralternativeaid) {
		this.PSupplieralternativeaid = PSupplieralternativeaid;
	}

	@Column(name = "P_BUYERIDS")
	public byte[] getPBuyerids() {
		return this.PBuyerids;
	}

	public void setPBuyerids(byte[] PBuyerids) {
		this.PBuyerids = PBuyerids;
	}

	@Column(name = "P_MANUFACTURERAID")
	public String getPManufactureraid() {
		return this.PManufactureraid;
	}

	public void setPManufactureraid(String PManufactureraid) {
		this.PManufactureraid = PManufactureraid;
	}

	@Column(name = "P_MANUFACTURERNAME")
	public String getPManufacturername() {
		return this.PManufacturername;
	}

	public void setPManufacturername(String PManufacturername) {
		this.PManufacturername = PManufacturername;
	}

	@Column(name = "P_ERPGROUPBUYER")
	public String getPErpgroupbuyer() {
		return this.PErpgroupbuyer;
	}

	public void setPErpgroupbuyer(String PErpgroupbuyer) {
		this.PErpgroupbuyer = PErpgroupbuyer;
	}

	@Column(name = "P_ERPGROUPSUPPLIER")
	public String getPErpgroupsupplier() {
		return this.PErpgroupsupplier;
	}

	public void setPErpgroupsupplier(String PErpgroupsupplier) {
		this.PErpgroupsupplier = PErpgroupsupplier;
	}

	@Column(name = "P_DELIVERYTIME", precision = 30, scale = 8)
	public BigDecimal getPDeliverytime() {
		return this.PDeliverytime;
	}

	public void setPDeliverytime(BigDecimal PDeliverytime) {
		this.PDeliverytime = PDeliverytime;
	}

	@Column(name = "P_SPECIALTREATMENTCLASSES")
	public byte[] getPSpecialtreatmentclasses() {
		return this.PSpecialtreatmentclasses;
	}

	public void setPSpecialtreatmentclasses(byte[] PSpecialtreatmentclasses) {
		this.PSpecialtreatmentclasses = PSpecialtreatmentclasses;
	}

	@Column(name = "P_ORDER")
	public Long getPOrder() {
		return this.POrder;
	}

	public void setPOrder(Long POrder) {
		this.POrder = POrder;
	}

	@Column(name = "P_APPROVALSTATUS")
	public Long getPApprovalstatus() {
		return this.PApprovalstatus;
	}

	public void setPApprovalstatus(Long PApprovalstatus) {
		this.PApprovalstatus = PApprovalstatus;
	}

	@Column(name = "P_CONTENTUNIT")
	public Long getPContentunit() {
		return this.PContentunit;
	}

	public void setPContentunit(Long PContentunit) {
		this.PContentunit = PContentunit;
	}

	@Column(name = "P_NUMBERCONTENTUNITS", precision = 30, scale = 8)
	public BigDecimal getPNumbercontentunits() {
		return this.PNumbercontentunits;
	}

	public void setPNumbercontentunits(BigDecimal PNumbercontentunits) {
		this.PNumbercontentunits = PNumbercontentunits;
	}

	@Column(name = "P_MINORDERQUANTITY")
	public Long getPMinorderquantity() {
		return this.PMinorderquantity;
	}

	public void setPMinorderquantity(Long PMinorderquantity) {
		this.PMinorderquantity = PMinorderquantity;
	}

	@Column(name = "P_MAXORDERQUANTITY")
	public Long getPMaxorderquantity() {
		return this.PMaxorderquantity;
	}

	public void setPMaxorderquantity(Long PMaxorderquantity) {
		this.PMaxorderquantity = PMaxorderquantity;
	}

	@Column(name = "P_ORDERQUANTITYINTERVAL")
	public Long getPOrderquantityinterval() {
		return this.POrderquantityinterval;
	}

	public void setPOrderquantityinterval(Long POrderquantityinterval) {
		this.POrderquantityinterval = POrderquantityinterval;
	}

	@Column(name = "P_PRICEQUANTITY", precision = 30, scale = 8)
	public BigDecimal getPPricequantity() {
		return this.PPricequantity;
	}

	public void setPPricequantity(BigDecimal PPricequantity) {
		this.PPricequantity = PPricequantity;
	}

	@Column(name = "P_NORMAL", length = 65535)
	public String getPNormal() {
		return this.PNormal;
	}

	public void setPNormal(String PNormal) {
		this.PNormal = PNormal;
	}

	@Column(name = "P_THUMBNAILS", length = 65535)
	public String getPThumbnails() {
		return this.PThumbnails;
	}

	public void setPThumbnails(String PThumbnails) {
		this.PThumbnails = PThumbnails;
	}

	@Column(name = "P_DETAIL", length = 65535)
	public String getPDetail() {
		return this.PDetail;
	}

	public void setPDetail(String PDetail) {
		this.PDetail = PDetail;
	}

	@Column(name = "P_LOGO", length = 65535)
	public String getPLogo() {
		return this.PLogo;
	}

	public void setPLogo(String PLogo) {
		this.PLogo = PLogo;
	}

	@Column(name = "P_DATA_SHEET", length = 65535)
	public String getPDataSheet() {
		return this.PDataSheet;
	}

	public void setPDataSheet(String PDataSheet) {
		this.PDataSheet = PDataSheet;
	}

	@Column(name = "P_OTHERS", length = 65535)
	public String getPOthers() {
		return this.POthers;
	}

	public void setPOthers(String POthers) {
		this.POthers = POthers;
	}

	@Column(name = "P_STARTLINENUMBER")
	public Long getPStartlinenumber() {
		return this.PStartlinenumber;
	}

	public void setPStartlinenumber(Long PStartlinenumber) {
		this.PStartlinenumber = PStartlinenumber;
	}

	@Column(name = "P_ENDLINENUMBER")
	public Long getPEndlinenumber() {
		return this.PEndlinenumber;
	}

	public void setPEndlinenumber(Long PEndlinenumber) {
		this.PEndlinenumber = PEndlinenumber;
	}

	@Column(name = "P_VARIANTTYPE")
	public Long getPVarianttype() {
		return this.PVarianttype;
	}

	public void setPVarianttype(Long PVarianttype) {
		this.PVarianttype = PVarianttype;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_PPG")
	public Long getPEurope1pricefactoryPpg() {
		return this.PEurope1pricefactoryPpg;
	}

	public void setPEurope1pricefactoryPpg(Long PEurope1pricefactoryPpg) {
		this.PEurope1pricefactoryPpg = PEurope1pricefactoryPpg;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_PTG")
	public Long getPEurope1pricefactoryPtg() {
		return this.PEurope1pricefactoryPtg;
	}

	public void setPEurope1pricefactoryPtg(Long PEurope1pricefactoryPtg) {
		this.PEurope1pricefactoryPtg = PEurope1pricefactoryPtg;
	}

	@Column(name = "P_EUROPE1PRICEFACTORY_PDG")
	public Long getPEurope1pricefactoryPdg() {
		return this.PEurope1pricefactoryPdg;
	}

	public void setPEurope1pricefactoryPdg(Long PEurope1pricefactoryPdg) {
		this.PEurope1pricefactoryPdg = PEurope1pricefactoryPdg;
	}

	@Column(name = "P_PRODUCTORDERLIMIT")
	public Long getPProductorderlimit() {
		return this.PProductorderlimit;
	}

	public void setPProductorderlimit(Long PProductorderlimit) {
		this.PProductorderlimit = PProductorderlimit;
	}

	@Column(name = "P_TAXCODE")
	public String getPTaxcode() {
		return this.PTaxcode;
	}

	public void setPTaxcode(String PTaxcode) {
		this.PTaxcode = PTaxcode;
	}

	@Column(name = "P_GALLERYIMAGES", length = 65535)
	public String getPGalleryimages() {
		return this.PGalleryimages;
	}

	public void setPGalleryimages(String PGalleryimages) {
		this.PGalleryimages = PGalleryimages;
	}

	@Column(name = "P_SEQUENCEID")
	public Long getPSequenceid() {
		return this.PSequenceid;
	}

	public void setPSequenceid(Long PSequenceid) {
		this.PSequenceid = PSequenceid;
	}

	@Column(name = "ACLTS")
	public Long getAclts() {
		return this.aclts;
	}

	public void setAclts(Long aclts) {
		this.aclts = aclts;
	}

	@Column(name = "PROPTS")
	public Long getPropts() {
		return this.propts;
	}

	public void setPropts(Long propts) {
		this.propts = propts;
	}

	@Column(name = "P_BASEPRODUCT")
	public Long getPBaseproduct() {
		return this.PBaseproduct;
	}

	public void setPBaseproduct(Long PBaseproduct) {
		this.PBaseproduct = PBaseproduct;
	}

	@Column(name = "P_PREVIOUSBASEPRODUCT")
	public Long getPPreviousbaseproduct() {
		return this.PPreviousbaseproduct;
	}

	public void setPPreviousbaseproduct(Long PPreviousbaseproduct) {
		this.PPreviousbaseproduct = PPreviousbaseproduct;
	}

	@Column(name = "HQABBR")
	public String getHqabbr() {
		return this.hqabbr;
	}

	public void setHqabbr(String hqabbr) {
		this.hqabbr = hqabbr;
	}

	@Column(name = "PARTNUMBER")
	public String getPartnumber() {
		return this.partnumber;
	}

	public void setPartnumber(String partnumber) {
		this.partnumber = partnumber;
	}

	@Column(name = "LINEABBR")
	public String getLineabbr() {
		return this.lineabbr;
	}

	public void setLineabbr(String lineabbr) {
		this.lineabbr = lineabbr;
	}

	@Column(name = "ISSHIPPABLE")
	public Byte getIsshippable() {
		return this.isshippable;
	}

	public void setIsshippable(Byte isshippable) {
		this.isshippable = isshippable;
	}

	@Column(name = "MSDS")
	public String getMsds() {
		return this.msds;
	}

	public void setMsds(String msds) {
		this.msds = msds;
	}

	@Column(name = "JSTDPKG")
	public String getJstdpkg() {
		return this.jstdpkg;
	}

	public void setJstdpkg(String jstdpkg) {
		this.jstdpkg = jstdpkg;
	}

	@Column(name = "DCUOM")
	public String getDcuom() {
		return this.dcuom;
	}

	public void setDcuom(String dcuom) {
		this.dcuom = dcuom;
	}

	@Column(name = "CLS")
	public String getCls() {
		return this.cls;
	}

	public void setCls(String cls) {
		this.cls = cls;
	}

	@Column(name = "GRPCODE")
	public String getGrpcode() {
		return this.grpcode;
	}

	public void setGrpcode(String grpcode) {
		this.grpcode = grpcode;
	}

	@Column(name = "WEIGHT")
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "WIDTH")
	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	@Column(name = "LENGTH")
	public String getLength() {
		return this.length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	@Column(name = "HEIGHT")
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "P_ISSELLABLETOCONSUMER")
	public Byte getPIssellabletoconsumer() {
		return this.PIssellabletoconsumer;
	}

	public void setPIssellabletoconsumer(Byte PIssellabletoconsumer) {
		this.PIssellabletoconsumer = PIssellabletoconsumer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Cartentry> getCartentries() {
		return this.cartentries;
	}

	public void setCartentries(Set<Cartentry> cartentries) {
		this.cartentries = cartentries;
	}

}
