package com.napa.model;
// Generated Nov 7, 2019 3:43:45 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "napaonline")
public class Role implements java.io.Serializable {

	private long roleId;
	private String customerRole;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Role() {
	}

	public Role(long roleId) {
		this.roleId = roleId;
	}

	public Role(long roleId, String customerRole, Set<Customer> customers) {
		this.roleId = roleId;
		this.customerRole = customerRole;
		this.customers = customers;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "customer_role", length = 128)
	public String getCustomerRole() {
		return this.customerRole;
	}

	public void setCustomerRole(String customerRole) {
		this.customerRole = customerRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
